/*-----------------------------------------------------------------------------
|| Tabellen-Skript der Tabelle C_DWH_PARAMETER
*/-----------------------------------------------------------------------------


  CREATE TABLE "DWH_DM"."C_DWH_PARAMETER"
   (	"DWH_LADE_ID" NUMBER NOT NULL ENABLE,
	"DWH_REC_SRC_SYSTEM" VARCHAR2(500 CHAR) NOT NULL ENABLE,
	"PAR_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"PAR_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"PAR_WERT" VARCHAR2(250 CHAR),
	"PAR_TYP" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	"PAR_FORMAT" VARCHAR2(30 CHAR),
	"PAR_BEDINGUNG" VARCHAR2(4000 CHAR) DEFAULT '~',
	"PAR_BESCHREIBUNG" VARCHAR2(4000 CHAR) DEFAULT '~' NOT NULL ENABLE,
	"PAR_DEFAULT" VARCHAR2(255 CHAR) DEFAULT '~',
	"PAR_WERTE_LISTE" VARCHAR2(4000 CHAR) DEFAULT '~',
	"PAR_CHANGED_ON" DATE,
	"PAR_CHANGED_BY" VARCHAR2(255 CHAR) DEFAULT '~'
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "DWH_DM"
  INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW
  DISTRIBUTE AUTO NO DUPLICATE ;
  CREATE UNIQUE INDEX "DWH_DM"."PAR_ID_IDX" ON "DWH_DM"."C_DWH_PARAMETER" ("PAR_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_DM" ;
  CREATE UNIQUE INDEX "DWH_DM"."PAR_NAME_IDX" ON "DWH_DM"."C_DWH_PARAMETER" ("PAR_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_DM" ;
ALTER TABLE "DWH_DM"."C_DWH_PARAMETER" ADD CONSTRAINT "PAR_PK" PRIMARY KEY ("PAR_ID")
  USING INDEX "DWH_DM"."PAR_ID_IDX"  ENABLE;
ALTER TABLE "DWH_DM"."C_DWH_PARAMETER" ADD CONSTRAINT "PAR_UK" UNIQUE ("PAR_NAME")
  USING INDEX "DWH_DM"."PAR_NAME_IDX"  ENABLE;

-------------------
-- Zugehörige Kommentare
-------------------

   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."DWH_LADE_ID" IS 'Schlüssel zu den Laufzeitinformationen des Prozesses der die Daten in die Tabelle eingefügt bzw. bearbeitet hat.';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."DWH_REC_SRC_SYSTEM" IS 'Spalte wird für die Markierung der Datenherkunft mitgeführt.';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_ID" IS 'Parameter ID';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_NAME" IS 'Unique Parameter Name ( in Grossbuchstaben )';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_WERT" IS 'Parameterwert als Text';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_FORMAT" IS 'Fall notwendig Format-string ( z.B. wenn PAR_TYP ist DATE ein Format, das in Kombination mit to_date() funtioniert )';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_BEDINGUNG" IS 'String, der bei einer Auswertung in der Form IF <Bedingung> THEN.. eine Boolsche Variable ergibt. Was da erlaubt ist, liegt an der Implementierung des einzelnen Parameters.';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_BESCHREIBUNG" IS 'Beschreibung. Sollte Format, typische Werte und Ort und Art der Anwendung enthalten.';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_DEFAULT" IS 'Fuktionscall, der einen Default im richtigen Format liefert';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_WERTE_LISTE" IS 'optionale Liste von erlaubten Werten ( z.B. TRUE und FALSE )';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_CHANGED_ON" IS 'Letzte Änderung am Parameter';
   COMMENT ON COLUMN "DWH_DM"."C_DWH_PARAMETER"."PAR_CHANGED_BY" IS 'Letze Änderung am Parameter von ...';
   COMMENT ON TABLE "DWH_DM"."C_DWH_PARAMETER"  IS 'Tabelle für Parameter im ODI ( oder OBIEE ). Kann zum Füllen von Variablen z.B. zur Ablaufkontrolle verwendet werden. Die Werte können im OBIEE geändert werden. ';

-------------------
-- Zugehörige Indizes
-------------------

-- PK- und UK-Indizes werden nicht separat ausgewiesen

-------------------
-- Zugehörige Grants
-------------------

  GRANT INSERT ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_MTD";
  GRANT DELETE ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_WORK";
  GRANT INSERT ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_WORK";
  GRANT SELECT ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_WORK";
  GRANT UPDATE ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_WORK";
  GRANT DELETE ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_MTD";
  GRANT SELECT ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_MTD";
  GRANT UPDATE ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_MTD";
  GRANT SELECT ON "DWH_DM"."C_DWH_PARAMETER" TO "OBIEE_BEDIAN";
  GRANT SELECT ON "DWH_DM"."C_DWH_PARAMETER" TO "HISI";
  GRANT DELETE ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_CORE";
  GRANT INSERT ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_CORE";
  GRANT SELECT ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_CORE";
  GRANT UPDATE ON "DWH_DM"."C_DWH_PARAMETER" TO "DWH_CORE";

