/*-----------------------------------------------------------------------------
|| Tabellen-Skript der Tabelle D_ETL_LADEPLAN
*/-----------------------------------------------------------------------------


  CREATE TABLE "DWH_DM"."D_ETL_LADEPLAN"
   (	"DETLLP_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"DWH_LADE_ID" NUMBER(38,0) NOT NULL ENABLE,
	"DWH_REC_SRC_SYSTEM" VARCHAR2(500 CHAR) NOT NULL ENABLE,
	"DWH_GUELTIG_VON" DATE DEFAULT TO_DATE('01.01.1111','DD.MM.YYYY') NOT NULL ENABLE,
	"DWH_GUELTIG_BIS" DATE DEFAULT TO_DATE('04.04.4444','DD.MM.YYYY'),
	"DWH_AKTIV" NUMBER,
	"LADEPLAN" VARCHAR2(255 CHAR) DEFAULT '~' NOT NULL ENABLE,
	"KEYWORDS" VARCHAR2(255 CHAR) DEFAULT '~',
	 CONSTRAINT "DETLLP_PK" PRIMARY KEY ("DETLLP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_DM"  ENABLE,
	 CONSTRAINT "DETLLP_UK" UNIQUE ("LADEPLAN", "DWH_GUELTIG_VON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_DM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "DWH_DM"
  INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW
  DISTRIBUTE AUTO NO DUPLICATE ;

-------------------
-- Zugehörige Kommentare
-------------------

   COMMENT ON COLUMN "DWH_DM"."D_ETL_LADEPLAN"."DETLLP_ID" IS 'technische ID des Ladeplans aus dem ODI-Repository';
   COMMENT ON COLUMN "DWH_DM"."D_ETL_LADEPLAN"."DWH_LADE_ID" IS 'Schlüssel zu den Laufzeitinformationen des Prozesses der die Daten in die Tabelle eingefügt bzw. bearbeitet hat.';
   COMMENT ON COLUMN "DWH_DM"."D_ETL_LADEPLAN"."DWH_REC_SRC_SYSTEM" IS 'Spalte wird für die Markierung der Datenherkunft mitgeführt.';
   COMMENT ON COLUMN "DWH_DM"."D_ETL_LADEPLAN"."DWH_GUELTIG_VON" IS 'Gültigkeitsdatum. Startzeitpunkt, ab dem ein Datensatz gültig ist.
Entspricht dem Zeitpunkt zu dem der Datenstand das DWH "betreten" hat (entsprechender Stage-Ladelauf).';
   COMMENT ON COLUMN "DWH_DM"."D_ETL_LADEPLAN"."DWH_GUELTIG_BIS" IS 'Zeitpunkt bis zu dem ein Datensatz gültig ist. Für aktuelle Datensätze.';
   COMMENT ON COLUMN "DWH_DM"."D_ETL_LADEPLAN"."DWH_AKTIV" IS 'Flag (0,1) um den letzten Stand eines Datensatzes zu markieren. Dieser ist hier auf 1 gesetzt.
Bereits beendete ZustÃ¤nde sind hier mit 0 markiert.';
   COMMENT ON COLUMN "DWH_DM"."D_ETL_LADEPLAN"."LADEPLAN" IS 'Name des jeweiligen Ladeplans';
   COMMENT ON COLUMN "DWH_DM"."D_ETL_LADEPLAN"."KEYWORDS" IS 'Schlüsselworte, die dem Ladeplan zugeordnet sind';
   COMMENT ON TABLE "DWH_DM"."D_ETL_LADEPLAN"  IS 'Dimension der Ladepläne die durch den ODI ausgeführt werden.
Wird für den Monitoring-Data Mart verwendet.';

-------------------
-- Zugehörige Indizes
-------------------

-- PK- und UK-Indizes werden nicht separat ausgewiesen

-------------------
-- Zugehörige Grants
-------------------

  GRANT SELECT ON "DWH_DM"."D_ETL_LADEPLAN" TO "OBIEE_BEDIAN";
  GRANT UPDATE ON "DWH_DM"."D_ETL_LADEPLAN" TO "DWH_WORK";
  GRANT SELECT ON "DWH_DM"."D_ETL_LADEPLAN" TO "DWH_WORK";
  GRANT INSERT ON "DWH_DM"."D_ETL_LADEPLAN" TO "DWH_WORK";
  GRANT DELETE ON "DWH_DM"."D_ETL_LADEPLAN" TO "DWH_WORK";
  GRANT SELECT ON "DWH_DM"."D_ETL_LADEPLAN" TO "HISI";

