/*-----------------------------------------------------------------------------
|| Tabellen-Skript der Tabelle D_ETL_STATUS
*/-----------------------------------------------------------------------------


  CREATE TABLE "DWH_DM"."D_ETL_STATUS"
   (	"DETLST_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"STATUS_CODE" VARCHAR2(1 CHAR),
	"STATUS" VARCHAR2(255 CHAR) DEFAULT '~',
	 CONSTRAINT "DETLST_PK" PRIMARY KEY ("DETLST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_DM"  ENABLE,
	 CONSTRAINT "DETLST_UK" UNIQUE ("STATUS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_DM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "DWH_DM"
  INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW
  DISTRIBUTE AUTO NO DUPLICATE ;

-------------------
-- Zugehörige Kommentare
-------------------

   COMMENT ON COLUMN "DWH_DM"."D_ETL_STATUS"."DETLST_ID" IS 'Künstlicher Schlüssel (ID).';
   COMMENT ON COLUMN "DWH_DM"."D_ETL_STATUS"."STATUS_CODE" IS 'Alle Status-Codes die bei der Ausführung von Ladeplänen und Sessions im ODI-Repository verwendet werden.';
   COMMENT ON COLUMN "DWH_DM"."D_ETL_STATUS"."STATUS" IS 'Sprechende deutsche Beschreibung des jeweiligen Status';
   COMMENT ON TABLE "DWH_DM"."D_ETL_STATUS"  IS 'Dimension der Status-Werte die in den ETL-Ausführungen durch den ODI verwendet werden.
Wird für den Monitoring-Data Mart verwendet.

Zur Dokumentation: https://docs.oracle.com/middleware/1221/odi/administer-develop/monitoring_executions.htm#CJAJBDFJ';

-------------------
-- Zugehörige Indizes
-------------------

-- PK- und UK-Indizes werden nicht separat ausgewiesen

-------------------
-- Zugehörige Grants
-------------------

  GRANT SELECT ON "DWH_DM"."D_ETL_STATUS" TO "OBIEE_BEDIAN";
  GRANT UPDATE ON "DWH_DM"."D_ETL_STATUS" TO "DWH_WORK";
  GRANT SELECT ON "DWH_DM"."D_ETL_STATUS" TO "DWH_WORK";
  GRANT INSERT ON "DWH_DM"."D_ETL_STATUS" TO "DWH_WORK";
  GRANT DELETE ON "DWH_DM"."D_ETL_STATUS" TO "DWH_WORK";
  GRANT SELECT ON "DWH_DM"."D_ETL_STATUS" TO "HISI";

