/*-----------------------------------------------------------------------------
|| Tabellen-Skript der Tabelle ETL_DELTA_LOG
*/-----------------------------------------------------------------------------


  CREATE TABLE "DWH_MTD"."ETL_DELTA_LOG"
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"ODI_ID" NUMBER NOT NULL ENABLE,
	"DWH_DELTA_DATE" DATE,
	"USAGE" NUMBER(1,0),
	"SCHEMA_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"TABLE_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"MAPPING_NAME" VARCHAR2(255 CHAR),
	"STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"PROCESSED_ROWS" NUMBER,
	"LOW_WATERMARK_SRC_DELTA" VARCHAR2(30 CHAR),
	"HIGH_WATERMARK_SRC_DELTA" VARCHAR2(30 CHAR),
	"SRC_DELTA_TYPE" VARCHAR2(20 CHAR),
	"EXEC_OWNER" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"CREATED_AT" DATE,
	"UPDATED_AT" DATE,
	"ODI_ID_PARENT" NUMBER,
	 CONSTRAINT "ETL_DELTA_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_MTD"  ENABLE,
	 CONSTRAINT "ETL_DELTA_LOG_UK" UNIQUE ("ODI_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_MTD"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "DWH_MTD" ;

-------------------
-- Zugehörige Kommentare
-------------------

   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."ID" IS 'Unique identity column';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."ODI_ID" IS 'ODI metadata repository reference, unique ID of ODI-Session fpr this entry';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."DWH_DELTA_DATE" IS 'DWH delta date used for ETL load';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."USAGE" IS 'Flag indicating this entry is deprecated';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."SCHEMA_NAME" IS 'Database schema of ETL target table';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."TABLE_NAME" IS 'Name of ETL target table';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."MAPPING_NAME" IS 'Name of ODI szenario used by this ETL';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."STATUS" IS 'Session execution state. Only rows showing "success" will be used for further ETL';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."PROCESSED_ROWS" IS 'Number of rows loaded into target table';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."LOW_WATERMARK_SRC_DELTA" IS 'Lower limit of this delta (format [date, timestamp, number] is dependant on SRC_DELTA_TYPE) from which on the delta loaded data from source';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."HIGH_WATERMARK_SRC_DELTA" IS 'Upper limit of this delta';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."SRC_DELTA_TYPE" IS 'Procedure, type [date, timestamp, number, full], for fetching delta time';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."EXEC_OWNER" IS 'Database schema for mapping execution';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."CREATED_AT" IS 'Time this entry has been created. Resembles loosely the mapping start date';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."UPDATED_AT" IS 'Time this entry has been updated. Resembles loosely the mapping finish time';
   COMMENT ON COLUMN "DWH_MTD"."ETL_DELTA_LOG"."ODI_ID_PARENT" IS 'ODI metadata repository reference of parent. Gefüllt nur für Tabellen mit Switch-Table Mechanismus, wenn die Mapping-Namen auf ...COPY oder ..CHANGED enden. Diese sind dann Childs von ...LISTE. Das ist wictig für die Ermittlung von Fehlern während der Laufzeit ( Auswertung des Error-Status auch über die Childs )';
   COMMENT ON TABLE "DWH_MTD"."ETL_DELTA_LOG"  IS 'All ETL mapping executions which processed data are logged in this table.';

-------------------
-- Zugehörige Indizes
-------------------

-- PK- und UK-Indizes werden nicht separat ausgewiesen

  CREATE BITMAP INDEX "DWH_MTD"."ETL_DELTA_LOG_SCHEMA_NAME_BIX" ON "DWH_MTD"."ETL_DELTA_LOG" ("SCHEMA_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_MTD" ;

  CREATE BITMAP INDEX "DWH_MTD"."ETL_DELTA_LOG_STATUS_BIX" ON "DWH_MTD"."ETL_DELTA_LOG" ("STATUS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_MTD" ;

  CREATE BITMAP INDEX "DWH_MTD"."ETL_DELTA_LOG_TABLE_NAME_BIX" ON "DWH_MTD"."ETL_DELTA_LOG" ("TABLE_NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "DWH_MTD" ;


-------------------
-- Zugehörige Grants
-------------------

  GRANT INSERT ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_WORK";
  GRANT DELETE ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_WORK";
  GRANT SELECT ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_WORK";
  GRANT SELECT ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_DM" WITH GRANT OPTION;
  GRANT INSERT ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_DM";
  GRANT UPDATE ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_DM";
  GRANT INSERT ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_CORE";
  GRANT UPDATE ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_CORE" WITH GRANT OPTION;
  GRANT UPDATE ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_WORK";
  GRANT SELECT ON "DWH_MTD"."ETL_DELTA_LOG" TO "DWH_CORE" WITH GRANT OPTION;

